/** @jsxImportSource https://esm.sh/react@18.2.0 */
import { useState } from "https://esm.sh/react@18.2.0";

const projects = [
  { title: "EATVERSE", tag: "Game", text: "A fast 2D arcade game built around eating, growing, strategy, poison, levels and one-more-run replayability." },
  { title: "Drawing Steps", tag: "AI + Art", text: "An idea for turning uploaded images into practical, step-by-step drawing guidance for faces, animals and objects." },
  { title: "Digital Land", tag: "Web App", text: "A real-world map concept where users can explore and interact with virtual land, designed with security and scalability in mind." },
  { title: "SmartCompare", tag: "Product", text: "A price-comparison concept that helps people discover better deals across online stores." },
];
const skills = ["Python", "SQL", "C++ / OOP", "Git & GitHub", "Linux", "Docker", "AWS", "Jenkins", "Kubernetes", "Terraform", "React", "TypeScript"];
function Arrow(){return <span aria-hidden="true">↗</span>}
export function App(){
 const [menu,setMenu]=useState(false),[dark,setDark]=useState(false);
 return <div className={dark?"min-h-screen bg-[#0b0d10] text-white":"min-h-screen bg-[#f7f5f0] text-[#171717]"}>
  <header className="fixed top-0 left-0 right-0 z-50 border-b border-black/10 dark:border-white/10 backdrop-blur-xl bg-[#f7f5f0]/80 dark:bg-[#0b0d10]/80"><nav className="max-w-6xl mx-auto px-5 md:px-8 h-16 flex items-center justify-between"><a href="#top" className="font-black tracking-tight text-lg">DIVAKAR<span className="text-lime-500">.</span></a><div className="hidden md:flex items-center gap-7 text-sm font-medium"><a href="#about">About</a><a href="#work">Work</a><a href="#art">Art</a><a href="#contact">Contact</a><button onClick={()=>setDark(!dark)} className="border rounded-full px-3 py-1.5">{dark?"☀":"☾"}</button></div><div className="md:hidden flex gap-2 items-center"><button onClick={()=>setDark(!dark)} className="border rounded-full px-3 py-1.5">{dark?"☀":"☾"}</button><button onClick={()=>setMenu(!menu)} className="text-xl px-2">☰</button></div></nav>{menu&&<div className="md:hidden px-5 pb-5 flex flex-col gap-4 text-sm font-semibold"><a onClick={()=>setMenu(false)} href="#about">About</a><a onClick={()=>setMenu(false)} href="#work">Work</a><a onClick={()=>setMenu(false)} href="#art">Art</a><a onClick={()=>setMenu(false)} href="#contact">Contact</a></div>}</header>
  <main id="top">
   <section className="min-h-[92vh] flex items-center pt-20"><div className="max-w-6xl mx-auto px-5 md:px-8 w-full py-20"><div className="max-w-4xl"><div className="inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-semibold mb-8"><span className="w-2 h-2 rounded-full bg-lime-400 animate-pulse"/> Building, learning & creating</div><h1 className="text-6xl sm:text-7xl md:text-9xl font-black tracking-[-0.07em] leading-[.84]">ENGINEER.<br/><span className="text-lime-500">ARTIST.</span><br/>BUILDER.</h1><p className="mt-9 text-lg md:text-xl max-w-2xl leading-relaxed opacity-70">I'm Divakar — an ECE graduate, creator and self-driven builder exploring software, AI, products and visual art.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#work" className="bg-lime-300 text-black rounded-full px-6 py-3 font-bold">Explore my work <Arrow/></a><a href="#contact" className="rounded-full border px-6 py-3 font-bold">Let's connect</a></div></div><div className="mt-16 flex flex-wrap gap-x-8 gap-y-3 text-xs uppercase tracking-[.2em] opacity-45 font-semibold"><span>SASTRA University</span><span>ECE · 2026</span><span>India</span><span>Digital + Traditional Art</span></div></div></section>
   <section id="about" className="max-w-6xl mx-auto px-5 md:px-8 py-28 md:py-36"><div className="grid md:grid-cols-[.7fr_1.3fr] gap-12 md:gap-24"><div><p className="text-xs uppercase tracking-[.25em] font-bold opacity-45">01 / About</p><h2 className="text-4xl md:text-6xl font-black tracking-tight mt-4">Curious by default.</h2></div><div className="text-xl md:text-2xl leading-relaxed opacity-75"><p>I like learning across disciplines instead of staying inside one box. My current path combines engineering fundamentals with software, DevOps, generative AI, product ideas and content creation.</p><p className="mt-6">Outside code, I teach and create pencil sketches and portraits. I'm interested in turning creative skills and technology into useful products people actually want to use.</p></div></div></section>
   <section id="work" className="bg-[#15171a] text-white py-28 md:py-36"><div className="max-w-6xl mx-auto px-5 md:px-8"><p className="text-xs uppercase tracking-[.25em] font-bold text-white/45">02 / Selected work</p><h2 className="text-4xl md:text-6xl font-black tracking-tight mt-4">Things I'm building.</h2><div className="grid md:grid-cols-2 gap-4 mt-12">{projects.map((p,i)=><article key={p.title} className="rounded-3xl border border-white/10 bg-white/[.04] p-7 md:p-9 min-h-64 flex flex-col justify-between"><div><div className="flex justify-between text-xs uppercase tracking-[.2em] text-white/40"><span>{String(i+1).padStart(2,"0")}</span><span>{p.tag}</span></div><h3 className="text-3xl font-black mt-12">{p.title}</h3><p className="mt-4 text-white/55 leading-relaxed max-w-md">{p.text}</p></div><div className="mt-8 text-lime-400 text-xl"><Arrow/></div></article>)}</div></div></section>
   <section id="art" className="py-28 md:py-36 border-b border-black/10"><div className="max-w-6xl mx-auto px-5 md:px-8"><div className="grid md:grid-cols-[1.1fr_.9fr] gap-14 items-center"><div><p className="text-xs uppercase tracking-[.25em] font-bold opacity-45">03 / Art & teaching</p><h2 className="text-5xl md:text-7xl font-black tracking-[-.05em] mt-4">Code on one side.<br/><span className="text-lime-500">Pencil on the other.</span></h2><p className="mt-7 text-lg leading-relaxed opacity-65 max-w-xl">I create pencil sketches and portraits, share drawing tutorials and teach students from basics to advanced techniques. I'm also exploring ways to turn that knowledge into digital courses, drawing guides and creative tools.</p><a href="#contact" className="inline-block mt-8 font-bold underline underline-offset-4">Work with me <Arrow/></a></div><div className="aspect-square rounded-[2rem] border bg-[#dedbd2] dark:bg-[#202327] flex items-center justify-center"><div className="text-center"><div className="text-8xl md:text-9xl">✎</div><p className="mt-5 font-black text-xl">ART × TECHNOLOGY</p><p className="text-sm opacity-50 mt-2">Sketch. Teach. Build.</p></div></div></div><div className="mt-10 grid md:grid-cols-3 gap-4"><div className="rounded-3xl border border-dashed p-10 min-h-52 flex items-center justify-center text-center opacity-60">Your artwork gallery<br/>will live here.</div><div className="rounded-3xl border border-dashed p-10 min-h-52 flex items-center justify-center text-center opacity-60">Portraits<br/>coming here.</div><div className="rounded-3xl border border-dashed p-10 min-h-52 flex items-center justify-center text-center opacity-60">More sketches<br/>coming here.</div></div></div></section>
   <section className="max-w-6xl mx-auto px-5 md:px-8 py-28 md:py-36"><div className="grid md:grid-cols-[.65fr_1.35fr] gap-12"><div><p className="text-xs uppercase tracking-[.25em] font-bold opacity-45">04 / Toolkit</p><h2 className="text-4xl md:text-6xl font-black mt-4 tracking-tight">Always learning.</h2></div><div><div className="flex flex-wrap gap-2">{skills.map(s=><span key={s} className="border rounded-full px-4 py-2.5 text-sm font-semibold">{s}</span>)}</div><p className="mt-8 opacity-55 leading-relaxed max-w-2xl">Current focus: Python, SQL, Linux, cloud and DevOps fundamentals, while continuing to build with React and TypeScript and learn generative AI.</p></div></div></section>
   <section id="contact" className="bg-lime-400 text-black py-24 md:py-32"><div className="max-w-6xl mx-auto px-5 md:px-8"><p className="text-xs uppercase tracking-[.25em] font-black opacity-50">05 / Contact</p><h2 className="text-5xl md:text-8xl font-black tracking-[-.06em] mt-4 max-w-4xl">Have an idea?<br/>Let's build it.</h2><p className="mt-7 max-w-xl text-lg opacity-70">I'm open to interesting projects, creative collaborations, product ideas and conversations around technology and art.</p><div className="mt-9 flex flex-wrap gap-3"><a href="mailto:hello@example.com" className="rounded-full bg-black text-white px-6 py-3 font-bold">Email me <Arrow/></a><a href="#top" className="rounded-full border border-black/20 px-6 py-3 font-bold">Back to top ↑</a></div></div></section>
  </main><footer className="bg-black text-white px-5 md:px-8 py-7"><div className="max-w-6xl mx-auto flex flex-col sm:flex-row justify-between gap-4 text-xs text-white/45"><span>© 2026 Divakar. Made with curiosity.</span><a href="/source" className="underline">view source</a></div></footer>
 </div>
}
